In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('ai_industry_summary_dirty.csv')

df.head()

,industry,avg_ai_adoption_rate,avg_productivity_change_percent,avg_ai_maturity_score,avg_ai_failure_rate,avg_jobs_displaced,avg_jobs_created,avg_customer_satisfaction
0,Agriculture,35.25,8.80,0.33,26.19,106.09,115.28,5.37
1,Consulting,34.52,NaN,0.33,26.46,106.33,116.06,5.35
2,education,35.23,8.79,0.33,26.13,111.25,122.58,5.37
3,Finance,38.35%,9.50,0.35,25.12,98.44,110.42,5.45
4,Healthcare,34.57,8.60,0.33,26.44,101.51,NaN,5.35

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   industry                         11 non-null     object
 1   avg_ai_adoption_rate             11 non-null     object
 2   avg_productivity_change_percent  9 non-null      float64
 3   avg_ai_maturity_score            11 non-null     float64
 4   avg_ai_failure_rate              11 non-null     float64
 5   avg_jobs_displaced               11 non-null     float64
 6   avg_jobs_created                 10 non-null     float64
 7   avg_customer_satisfaction        11 non-null     object
dtypes: float64(5), object(3)
memory usage: 836.0+ bytes

In [ ]:
df.isnull().sum()

industry                           0
avg_ai_adoption_rate               0
avg_productivity_change_percent    2
avg_ai_maturity_score              0
avg_ai_failure_rate                0
avg_jobs_displaced                 0
avg_jobs_created                   1
avg_customer_satisfaction          0
dtype: int64

In [ ]:
df['avg_productivity_change_percent'] = df['avg_productivity_change_percent'].fillna(df['avg_productivity_change_percent'].median())

df['avg_jobs_created'] = df['avg_jobs_created'].fillna(df['avg_jobs_created'].median())

In [ ]:
df.isnull().sum()

industry                           0
avg_ai_adoption_rate               0
avg_productivity_change_percent    0
avg_ai_maturity_score              0
avg_ai_failure_rate                0
avg_jobs_displaced                 0
avg_jobs_created                   0
avg_customer_satisfaction          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['avg_ai_adoption_rate'].unique()

array(['35.25', '34.52', '35.23', '38.35%', '34.57', '35.26', '34.73',
       '34.7', '42.47'], dtype=object)

In [ ]:
df['avg_ai_adoption_rate'] = df['avg_ai_adoption_rate'].str.replace('%', '')

In [ ]:
df['avg_ai_adoption_rate'] = pd.to_numeric(df['avg_ai_adoption_rate'])

In [ ]:
df['avg_ai_adoption_rate']

0     35.25
1     34.52
2     35.23
3     38.35
4     34.57
5     35.26
6     34.73
7     34.70
8     42.47
10    34.52
Name: avg_ai_adoption_rate, dtype: float64

In [ ]:
df['avg_customer_satisfaction'].unique()

array(['5.37', '5.35', '5.45', '5.4', '5.39', '5,39', '5.64'],
      dtype=object)

In [ ]:
df['avg_customer_satisfaction'] = df['avg_customer_satisfaction'].str.replace(',', '.')

In [ ]:
df['avg_customer_satisfaction'] = pd.to_numeric(df['avg_customer_satisfaction'])

In [ ]:
df['avg_customer_satisfaction']

0     5.37
1     5.35
2     5.37
3     5.45
4     5.35
5     5.40
6     5.39
7     5.39
8     5.64
10    5.35
Name: avg_customer_satisfaction, dtype: float64

In [ ]:
df['industry'].unique()

array([' Agriculture ', 'Consulting', 'education', 'Finance',
       'Healthcare', 'Logistics', 'Manufactring', 'Retail', 'Technology',
       'Consulting '], dtype=object)

In [ ]:
df['industry'] = df['industry'].str.strip()

In [ ]:
df['industry'].unique()

array(['Agriculture', 'Consulting', 'education', 'Finance', 'Healthcare',
       'Logistics', 'Manufactring', 'Retail', 'Technology'], dtype=object)

In [ ]:
Q1 = df.select_dtypes(include='number').quantile(0.25)
Q2 = df.select_dtypes(include='number').quantile(0.50)
Q3 = df.select_dtypes(include='number').quantile(0.75)

print("Q1:")
print(Q1)

print("Q2:")
print(Q2)

print("Q3:")
print(Q3)

Q1:
avg_ai_adoption_rate                34.6025
avg_productivity_change_percent      8.8475
avg_ai_maturity_score                0.3300
avg_ai_failure_rate                 26.1450
avg_jobs_displaced                 106.1500
avg_jobs_created                   110.5900
avg_customer_satisfaction            5.3550
Name: 0.25, dtype: float64
Q2:
avg_ai_adoption_rate                34.980
avg_productivity_change_percent      9.050
avg_ai_maturity_score                0.330
avg_ai_failure_rate                 26.325
avg_jobs_displaced                 108.790
avg_jobs_created                   114.235
avg_customer_satisfaction            5.380
Name: 0.5, dtype: float64
Q3:
avg_ai_adoption_rate                35.2575
avg_productivity_change_percent      9.1100
avg_ai_maturity_score                0.3300
avg_ai_failure_rate                 26.4250
avg_jobs_displaced                 114.2100
avg_jobs_created                   116.0600
avg_customer_satisfaction            5.3975
Name: 0.75, dtype: float64

In [ ]:
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower:")
print(lower)

print("Upper:")
print(upper)

Lower:
avg_ai_adoption_rate                33.62000
avg_productivity_change_percent      8.45375
avg_ai_maturity_score                0.33000
avg_ai_failure_rate                 25.72500
avg_jobs_displaced                  94.06000
avg_jobs_created                   102.38500
avg_customer_satisfaction            5.29125
dtype: float64
Upper:
avg_ai_adoption_rate                36.24000
avg_productivity_change_percent      9.50375
avg_ai_maturity_score                0.33000
avg_ai_failure_rate                 26.84500
avg_jobs_displaced                 126.30000
avg_jobs_created                   124.26500
avg_customer_satisfaction            5.46125
dtype: float64

In [ ]:
numeric = df.select_dtypes(include='number')

outliers = (numeric < lower) | (numeric > upper)

outliers.sum()

avg_ai_adoption_rate               2
avg_productivity_change_percent    1
avg_ai_maturity_score              2
avg_ai_failure_rate                2
avg_jobs_displaced                 1
avg_jobs_created                   1
avg_customer_satisfaction          1
dtype: int64

In [ ]:
for col in numeric.columns:
    print(col)
    print(df.loc[outliers[col], col].values)

avg_ai_adoption_rate
[38.35 42.47]
avg_productivity_change_percent
[11.17]
avg_ai_maturity_score
[0.35 4.1 ]
avg_ai_failure_rate
[25.12 23.56]
avg_jobs_displaced
[133.74]
avg_jobs_created
[149.08]
avg_customer_satisfaction
[5.64]

In [ ]:
df.to_excel('ai_industry_cleaned.xlsx', index=False)